version: '3.7'

services:

  proxy:
    image: lerenn/lets-encrypt-reverse-proxy

    container_name: nginx

    restart: unless-stopped

    environment:
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - CERT1=${CERT1}

    volumes:
      - ${PROXY_DATA_LOCATION}/letsencrypt:/etc/letsencrypt
      - ${PROXY_DATA_LOCATION}/sites-enabled:/etc/nginx/sites-enabled
      - ${PROXY_DATA_LOCATION}/snippets:/etc/nginx/snippets
    
    ports:
      - "80:80"
      - "443:443"
    
    networks:
      - frontend
      - backend

  portainer:
    image: portainer/portainer

    container_name: portainer

    restart: always

    ports:
      - "9000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PROXY_DATA_LOCATION}/portainer:/data

    networks:
      - backend
       
    depends_on:
      - proxy

networks:
  frontend:
    external:
      name: ${NETWORK:-webproxy}
  backend:
    internal: true
    name: ${SERVICE_NETWORK:-portainer}  

  